[package]
name = "snake"
version = "0.1.0"
authors = ["Davis Kregers <davis.kregers@edurio.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
piston_window = "0.105.0"
