[package]
name = "blockchain"
version = "0.1.0"
authors = ["Davis Kregers <davis.kregers@edurio.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
sha2 = "*"
